name: CI Push Docker Image
on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE_NAME: crmop/crm-event-handler

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read

    outputs:
      docker_image: ${{ steps.get-image-tag.outputs.image }}

    steps:
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          flavor: |
            latest=false
          images: |
            ${{ steps.login-ecr.outputs.registry }}/${{ env.DOCKER_IMAGE_NAME }}
          tags: |
            type=schedule
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Get Image tag
        id: get-image-tag
        run: |
          echo "image=$(echo "$DOCKER_METADATA_OUTPUT_TAGS" | tail -n1)" >> $GITHUB_OUTPUT

      - name: Create summary
        id: create-summary
        run: |
          echo '🚀 Image pushed to `${{ steps.get-image-tag.outputs.image }}`' >> $GITHUB_STEP_SUMMARY
